http:
  routers:
    nginx:
      rule: "PathPrefix(`/`)"
      service: frontend_service
      entryPoints:
        - web

    django:
      rule: "Header(`is-backend`, `1`)"
      service: backend_service
      entryPoints:
        - backend

  services:
    frontend_service:
      loadBalancer:
        servers:
          - url: "http://nginx_frontend:8080"

    backend_service:
      loadBalancer:
        servers:
          - url: "http://django_backend:8000"
