entryPoints:
  web:
    address: ":80"
  backend:
    address: ":8090"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true
